version: '3'

services:
  mysql:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=initdb
  app:
    build: ./app
    links:
      - mysql
    ports:
      - "5000:5000"
